[General]
ListFileExtName         = ["*.c","*.h","*.cpp"]
BoolCheckVariableName   = true
BoolCheckFunctionName   = true
BoolCheckFileName       = false

[Rule]
EnumFileName            = 0 # 0: Default (UpperCamelCase)
                            # 1: UpperCamelCase
                            # 3: lower-seperated

EnumFunctionName        = 0 # 0: Default (UpperCamelCase)
                            # 1: UpperCamelCase
                            # 2: lowerCamelCase
                            # 3: lower-seperated

EnumVariableName        = 4 # 0: Default (UpperCamelCase)
                            # 1: UpperCamelCase
                            # 2: lowerCamelCase
                            # 3: lower-seperated
                            # 4: Hungarian
[WhiteList]
BoolAllowedUnderscopeChar    = false

ListFunctionPrefix           = [ "_",
                                 "__" ]
ListVariablePrefix           = [ "m_" ]

IgnoreFunctions              = ["main"]


[HungarianList]
# C Primitive Type
"size_t"                 = "n"
"int8_t"                 = "i8"
"int16_t"                = "i16"
"int32_t"                = "i32"
"int64_t"                = "i64"
"uint8_t"                = "u8"
"uint16_t"               = "u16"
"uint32_t"               = "u32"
"uint64_t"               = "u64"
"char"                   = "c"
"char*"                  = "sz"
"wchar_t*"               = "wsz"
"_Bool"                  = "b"
"bool"                   = "b"
"wchar_t"                = "wc"
"signed char"            = "sc"
"unsigned char"          = "uc"
"short"                  = "s"
"short int"              = "si"
"signed short"           = "ss"
"signed short int"       = "ssi"
"unsigned short"         = "us"
"unsigned short int"     = "usi"
"int"                    = "i"
"signed"                 = "s"
"signed int"             = "si"
"unsigned"               = "u"
"unsigned int"           = "ui"
"long"                   = "l"
"long int"               = "li"
"signed long"            = "sl"
"signed long int"        = "sli"
"unsigned long"          = "ul"
"unsigned long int"      = "uli"
"long long"              = "ll"
"long long int"          = "lli"
"signed long long"       = "sll"
"signed long long int"   = "slli"
"unsigned long long"     = "ull"
"unsigned long long int" = "ulli"
"float"                  = "f"
"double"                 = "d"
"long double"            = "ld"

# Windows Type
"ULONG"                  = "ul"
"DWORD"                  = "dw"
"DWORD64"                = "dw64"
"WORD"                   = "w"
"CHAR"                   = "c"
"BYTE"                   = "by"
"HANDLE"                 = "h"
"BOOLEAN"                = "b"
"LONGLONG"               = "ll"



