[General]
FileExtName         = ["*.c","*.h","*.cpp"]
CheckVariableName   = true
CheckFunctionName   = false
CheckFileName       = true

[Rule]
FileName            = 1 # 0: Default (UpperCamelCase)
                        # 1: UpperCamelCase
                        # 2: lower-seperated

FunctionName        = 3 # 0: Default (UpperCamelCase)
                        # 1: UpperCamelCase
                        # 2: lowerCamelCase
                        # 3: lower-seperated

VariableName        = 2 # 0: Default ()
                        # 1: Hungarian

[WhiteList]
FunctionPrefix      = [ "_",
                        "__" ]
VariablePrefix      = [ "m_" ]

[HungarianList]
# C Primitive Type
int8_t                 = "i8"
int16_t                = "i16"
int32_t                = "i32"
uint8_t                = "u8"
uint16_t               = "u16"
uint32_t               = "u32"
char                   = "c"
signed-char            = "sc"
unsigned-char          = "uc"
short                  = "s"
short-int              = "si"
signed-short           = "ss"
signed-short-int       = "ssi"
unsigned-short         = "us"
unsigned-short-int     = "usi"
int                    = "i"
signed                 = "s"
signed-int             = "si"
unsigned               = "u"
unsigned-int           = "ui"
long                   = "l"
long-int               = "li"
signed-long            = "sl"
signed-long-int        = "sli"
unsigned-long          = "ul"
unsigned-long-int      = "uli"
long-long              = "ll"
long-long-int          = "lli"
signed-long-long       = "sll"
signed-long-long-int   = "slli"
unsigned-long-long     = "ull"
unsigned-long-long-int = "ulli"
float                  = "f"
double                 = "d"
long-double            = "ld"
_Bool                  = "b"
bool                   = "b"
wchar_t                = "wc"

# Windows Type
ULONG                  = "ul"
DWORD                  = "dw"
DWORD64                = "dw64"
WORD                   = "w"
CHAR                   = "c"
BYTE                   = "by"
HANDLE                 = "h"
BOOLEAN                = "b"
LONGLONG               = "ll"


